### ISSUE TITLE
Drop 32-bit support

### ISSUE THREAD

**Issue by gliwka** [LocateTech/hyperscan-java#45]
Centos 7 is being used now to be able to build hyper scan with AVX512 support.

Devtoolset-7 is being used for this to have a modern gcc based toolchain. Since RedHat dropped 32-bit support, we're not able to build 32-bit versions any more and thus dropping the support.

**Comment by eliaslevy** [comment]
👍

**Comment by eliaslevy** [comment]
Finally got around to testing the 0.5.0 jars.  Alas, they don't work for us.  We are using CentOS 7.4, while it seems the new shared libs are being built using the `centos:centos7` Docker image, which maps to CentOS 7.5.1804.  It is probably safer to build against an earlier version of CentOS 7.  E.g. CentOS 7.4 also uses Glibc 2.17.

For now it looks like we'll have to stay on the previous version of hyperscan-java or build our own.

**Comment by gliwka** [comment]
Thank you for your comment, I will look into it :-)

**Comment by eliaslevy** [comment]
After some further testing, we found out the jar actually works in CentOS 7.4.  We were running into an issue where the old library was still loaded in the process.

As for performance, as of this moment we haven't seen an increase, even though we are executing it on c5 instances with AVX-512 support.  We'll run a few more tests.
