### ISSUE TITLE
Double free issue using Scanner::close and Database::close

### ISSUE THREAD

**Issue by ajcave** [LocateTech/hyperscan-java#49]
First, thanks a lot for these bindings! I was able to get a pretty significant performance improvement in my use-case quite easily by switching from the naive "loop over all the regexes" algorithm to using these hyperscan bindings :)

In my use-case I was creating a lot of Scanners in try-with-resources blocks one after the other. (I know it's not ideal to be re-allocating them unnecessarily, but it was the quickest way to a working prototype in my case). And sometimes I was getting an `InvalidParameterException("An invalid parameter has been passed. Is scratch allocated?")` from scanning.

I'm pretty sure I've tracked this down to the [implementation of `close()` and `finalize()`](https://github.com/LocateTech/hyperscan-java/blob/d0a08fdcf2e2840ef0639cd24d05b545b7131443/src/main/java/com/gliwka/hyperscan/wrapper/Scanner.java#L129)

The problem is, when `close()` is called (via try-with-resources or otherwise) the scratch space is freed, and then at some later point `finalize()` might run and trigger a double free. My working theory is that in my case, it sometimes happened that between closing the first Scanner and executing the finalizer a new Scanner was allocated at the same address, and the second free in the finalizer deallocated the new one I was just about to use!

**Comment by gliwka** [comment]
Thank you very much for your input, glad you find the bindings useful. 

I'm currently swamped with work, but will investigate this on the weekend. The crude close() and finalize() implementations definitely need to be reworked. 

Could you maybe provide a unit test or piece of code so I can easily reproduce the issue? This could speed things up quite a lot.

**Comment by eliaslevy** [comment]
Could also just check `scratch` is not `null` before calling `HyperscanLibrary.INSTANCE.hs_free_scratch(scratch)` and then set it to `null`.

**Comment by gliwka** [comment]
I've released v0.5.1 with the fix. I just promoted the release on maven central, it should propagate within the next 10 minutes.

Please let me know if this solves the issue or if it still persists.
